name: DDF Tools action
description: Do stuff related to deCONZ DDF.
author: Zehir
branding:
  icon: check
  color: green
inputs:
  mode:
    default: action
    description: 'Mode to run the action in (action, ci-pr, ci-push)'

  # # Common options for validate and bundle
  source-devices-path:
    default: devices
    description: input path of DDF files
  source-search-pattern:
    description: input search pattern
    default: '**/*.json'
  source-ignore-pattern:
    description: ignore files that match this pattern

  # # Bundler options
  bundler-enabled:
    description: Enable bundling of DDF files
    default: 'true'
  bundler-output-path:
    description: output path of bundled DDF files if not provided will keep them in memory before uploading if enabled
  bundler-sign-keys:
    description: comma seperated list of private keys to sign the bundle with
  bundler-file-modified-method:
    description: 'Method to use to mark the files as modified (gitlog, mtime, ctime)'
    default: gitlog

  # # Bundler Validation options
  bundler-validation-enabled:
    description: Enable validation of DDF files
    default: 'true'
  bundler-validation-strict:
    description: Validate all files even if they have the ddfvalidate option to false
    default: 'false'
  bundler-validation-enforce-uuid:
    description: Enforce unique IDs in the DDF files
    default: 'true'

  # # Upload options
  upload-enabled:
    description: Enable upload of DDF bundles
    default: 'false'
  upload-input-path:
    description: input path of DDF bundles to upload if not provided will use the output bundles of the bundler
  upload-url:
    description: URL to upload the DDF bundles to
  upload-token:
    description: Token to use for the upload

  # # CI options
  # ## PR options
  ci-pr-validate:
    description: Validate the DDF files in a PR
    default: 'true'
  ci-pr-draft-bundle:
    description: Create a draft bundle for the PR
    default: 'true'
  ci-pr-release-bundle:
    description: Release the bundle when PR merged
    default: 'true'
  ci-pr-affected-bundle-list:
    description: Add a message on the PR with the list of affected DDF
    default: 'true'

  # ## Push options
  ci-push-validate:
    description: Validate the DDF files on push
    default: 'true'
  ci-push-release-bundle:
    description: Release the bundle when PR merged
    default: 'true'

runs:
  using: node20
  main: dist/index.js
