name: DDF Tools action
description: Do stuff related to deCONZ DDF.
author: Zehir
branding:
  icon: check
  color: green
inputs:
  mode:
    default: push
    description: 'Mode to run the action in (manual, push, pull_request)'

  # # Common options for validate and bundle
  source-devices-path:
    default: devices
    description: input path of DDF files
  source-search-pattern:
    description: input search pattern
    default: '**/*'
    # default: '**/*.(json|js|md)'
  source-ignore-pattern:
    description: ignore files that match this pattern

  # # Bundler options
  bundler-enabled:
    description: Enable bundling of DDF files
    default: 'true'
  bundler-output-path:
    description: output path of bundled DDF files if not provided will keep them in memory before uploading if enabled
  bundler-output-directory-format:
    description: 'Format of the output directory structure (source-tree, flat)'
    default: flat
  bundler-output-file-format:
    description: 'Format of the output files names (name, name-hash, hash)'
    default: hash
  bundler-sign-keys:
    description: comma seperated list of private keys to sign the bundle with
  bundler-file-modified-method:
    description: 'Method to use to mark the files as modified (gitlog, mtime, ctime)'
    default: gitlog

  # # Bundler Validation options
  bundler-validation-enabled:
    description: Enable validation of DDF files
    default: 'true'
  bundler-validation-strict:
    description: Validate all files even if they have the ddfvalidate option to false
    default: 'false'
  bundler-validation-enforce-uuid:
    description: Enforce unique IDs in the DDF files
    default: 'true'
  bundler-validation-warn-unused-files:
    description: Send a warning if a file is not used in any bundle
    default: 'true'

  # # Upload options
  upload-store-enabled:
    description: Enable upload of DDF bundles
    default: 'false'
  upload-store-input-path:
    description: input path of DDF bundles to upload if not provided will use the output bundles of the bundler
  upload-store-url:
    description: URL to upload the DDF bundles to
  upload-store-token:
    description: Token to use for the upload
  upload-store-status:
    description: Store system signature to use for the upload (alpha, beta, stable)
    default: alpha
  upload-store-toolbox-url:
    description: URL to upload the DDF toolbox to
    default: 'https://deconz-community.github.io/ddf-tools/#/'

  upload-artifact-enabled:
    description: Upload the output path as an artifact
    default: 'false'
  upload-artifact-filter:
    description: Comma seperated list of status to use for the artifact upload (added, modified, unchanged)
    default: added,modified,unchanged
  upload-artifact-retention-days:
    description: Duration of the artifact in days
    default: '3'

runs:
  using: node20
  main: dist/index.js
