name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Update Release tags
        uses: teunmooij/github-versioned-release@v1
        with:
          include: '(dist|template)/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
