name: Continuous integration Add comments

on:
  workflow_run:
    workflows: ["Continuous integration"]
    types:
      - completed

jobs:
  use_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: my-script
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "interaction_data"
            })[0];
            if(matchArtifact == undefined) {
              throw new Error("No artifact found");
            }
            let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/interaction_data.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip interaction_data.zip


      - name: 'Comment on PR'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            let issue_number = JSON.parse(fs.readFileSync('./interaction_data.json'));
            console.log(issue_number);

