name: Continuous integration Add comments

on:
  workflow_run:
    workflows: ["Continuous integration"]
    types:
      - completed

jobs:
  use_output:
    runs-on: ubuntu-latest
    steps:
      - name: Use output interaction_data_pull_request
        run: echo "${{ github.event.workflow_run.outputs.interaction_data_pull_request }}"

      - name: Use output interaction_data_push
        run: echo "${{ github.event.worflow_run.outputs.interaction_data_push }}"
      
      - name: Use output interaction_data_workflow_dispatch
        run: echo "${{ github.event.workflow_run.outputs.interaction_data_workflow_dispatch }}"

      - uses: actions/github-script@v7
        id: my-script
        with:
          script: |
            console.log(`Output: ${JSON.stringify(context, null, 2)}`);