# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Continuous integration

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          run_install: true

      - name: Build
        run: pnpm build

      - name: Run DDF Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        id: ddf_ci_workflow_dispatch
        uses: ./
        with:
          mode: manual
          source-devices-path: 'tests'
          source-ignore-pattern: '**/*([a-z_])(invalid|unused).(json|md)'
          
          auto-commit-uuid: 'true'
          bundler-validation-enforce-uuid: 'false'
          # upload-store-enabled: true
          upload-store-url: ${{ secrets.UPLOAD_URL }}
          upload-store-token: ${{ secrets.UPLOAD_TOKEN }}
          upload-artifact-enabled: true
          upload-artifact-retention-days: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DDF Push Action
        if: github.event_name == 'push'
        id: ddf_ci_push
        uses: ./
        with:
          mode: push
          source-devices-path: 'tests'
          source-ignore-pattern: '**/*([a-z_])(invalid|unused).(json|md)'
          auto-commit-uuid: 'true'
          bundler-validation-enforce-uuid: 'false'
          upload-store-url: ${{ secrets.UPLOAD_URL }}
          upload-store-token: ${{ secrets.UPLOAD_TOKEN }}
          # upload-artifact-enabled: true
          # upload-artifact-filter: 'added,modified'
          # upload-artifact-retention-days: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DDF Pull Request Interaction
        id: ddf_ci_pull_request
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          mode: pull_request
          source-devices-path: 'tests'
          source-ignore-pattern: '**/*([a-z_])(invalid|unused).(json|md)'
          upload-artifact-enabled: true
          upload-artifact-filter: 'added,modified'
          upload-artifact-retention-days: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish
        if: github.event_name == 'push'
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release tags
        uses: JasonEtco/build-and-tag-action@v2
        if: github.event_name == 'push' && steps.changesets.outcome == 'success' && steps.changesets.outputs.published == 'true'
        with:
          tag_name: ${{ format('v{0}', fromJSON(steps.changesets.outputs.publishedPackages)[0].version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      interaction_data_pull_request: ${{ steps.ddf_ci_pull_request.outputs.interaction_data }}
      interaction_data_push: ${{ steps.ddf_ci_push.outputs.interaction_data }}
      interaction_data_workflow_dispatch: ${{ steps.ddf_ci_workflow_dispatch.outputs.interaction_data }}